wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.43.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1751700788
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.17.5
      6: 4.43.4
      8:
      - 4
      - 5
      13: darwin-arm64
